#!/bin/sh
# arch-tag: dfshints: display useful hints

cat <<EOF
Here are some useful DFS commands:
Command                     Description
--------------------------- -------------------------------------------------
dfshelp                     Access primary DFS documentation. 
dfshints                    Display this information
reboot                      Reboot the system
elinks, lftp                Web browser / FTP client
/etc/init.d/lvm start       Initialize LVM subsystem
/etc/init.d/discover start  Autodetect hardware, method 1
/etc/init.d/hotplug start   Initialize support for USB devices, 
                            autodetect hardware method 2
/etc/init.d/pcmcia start    Initialize PCMCIA subsystem
nano, vim, joe, or emacs    Text editors
Alt-F1 through Alt-F6       Switch to other virtual terminals
Alt-F7, Alt-F8              Display log (F7) or debug (F8) messages
EOF
