#!/bin/sh

# List the soft prerequisites here.  This is a space separated list of
# names, of scripts that are in the same directory as this one, that
# must be run before this one can be.
#
PREREQ="udev_helper"
MOUNTLOC=/dfs-roottest

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

canmount()
{
    mount -n -t iso9660 -o ro $1 $MOUNTLOC
}

checkvalidity()
{
    echo -n "Scanning $1: "
    if canmount $1; then
        if cmp /marker $MOUNTLOC/opt/dfsruntime/marker; then
            umount $MOUNTLOC
            echo "Found DFS CD."
            return 0
        else
            umount $MOUNTLOC
            echo "Found a CD, but not the correct DFS one."
            return 1
        fi
    else
        echo "$1: Not mountable (empty drive, not a CD-ROM, or wrong device)"
        return 1
    fi
}

echo ""
echo " *** Welcome to Debian From Scratch (DFS) ***"
echo "Initial RAM disk (format 2, with initramfs-tools) booting."
echo ""
ls -l /dev/root
if checkvalidity /dev/root
    then echo "/dev/root is the correct CD; using it."
    exit 0
fi

cat <<EOF
Scanning for DFS CD.  The root= kernel parameter can override this scan
if there is trouble.
EOF

OLDCWD=`pwd`
cd /sys/block
for DEVICE in *; do
    if [ `cat $DEVICE/removable` = 1 ]; then
        if checkvalidity /dev/$DEVICE; then
            cd $OLDCWD
            rm /dev/root || true
            ln -sf /dev/$DEVICE /dev/root
            exit 0
        fi
    fi
done

cd $OLDCWD
echo ""
echo "Could not find a DFS CD.  Terminating."

exit 0

