#!/bin/sh

# List the soft prerequisites here.  This is a space separated list of
# names, of scripts that are in the same directory as this one, that
# must be run before this one can be.
#
PREREQ="udev_helper"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /dfs_startup_funcs

echo "------------------------------------------------------------"
echo " *** Welcome to Debian From Scratch (DFS) ***"
echo "Initial RAM disk (format 2, with initramfs-tools) booting."
echo "------------------------------------------------------------"

while true; do
    if scandevices; then 
        ln -sf $DFSDEVICE /dev/root
        exit 0
    else
        echo ""
        echo "Could not find a DFS CD.  Sleeping 10 seconds to let devices"
        echo "settle, then will try again."
        sleep 10
    fi
done

exit 0


