#!/bin/sh

. /dfs_startup_funcs
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH
rootmnt=/realroot

echo "------------------------------------------------------------"
echo " *** Welcome to Debian From Scratch (DFS) ***"
echo "Initial RAM disk (format 2, without initramfs-tools) booting."
echo "------------------------------------------------------------"

mount -n -t proc none /proc
mount -n -t sysfs none /sys

if scandevices; then 
    umount /sys
    umount /proc
    createrd
    cd $rootmnt
    pivot_root . initrd
    cd .
    cd /
    echo " *** Now booting system from $DFSDEVICE ***"
    exec /sbin/init "$@"
else
    umount /sys
    umount /proc
    echo ""
    echo "Could not find a DFS CD.  Terminating."
    exit 1
fi


