Document: dfsbuild
Title: Debian dfsbuild Manual
Author: <insert document author here>
Abstract: This manual describes what dfsbuild is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dfsbuild/dfsbuild.sgml.gz

Format: postscript
Files: /usr/share/doc/dfsbuild/dfsbuild.ps.gz

Format: text
Files: /usr/share/doc/dfsbuild/dfsbuild.text.gz

Format: HTML
Index: /usr/share/doc/dfsbuild/html/index.html
Files: /usr/share/doc/dfsbuild/html/*.html

  
